---

- name: Get latest AWX operator release
  when: awx_operator_tag is not defined or awx_operator_tag | length > 0
  block:
    - name: Get AWX operator releases
      ansible.builtin.uri:
        url: https://api.github.com/repos/ansible/awx-operator/releases
        return_content: true
      register: awx_operator_releases
    - name: Get latest release and set as target tag
      ansible.builtin.set_fact:
        awx_operator_tag: "{{ awx_operator_releases['json'][0]['tag_name'] }}"

- name: Deploy kustomization.yaml template
  ansible.builtin.template:
    src: kustomization.yaml.j2
    dest: "{{ kustomize_directory }}/kustomization.yaml"
    mode: "0644"

- name: Apply ressources from kustomize directory
  ansible.builtin.command:
    cmd: kubectl apply -k {{ kustomize_directory }}
  register: apply_ressources_result
  changed_when: (apply_ressources_result.stdout_lines | select('search', 'created')) or (apply_ressources_result.stdout_lines | select('search', 'changed'))

- name: Wait for running state of awx-operator-controller-manager pods (timeout set to 5 minutes)
  kubernetes.core.k8s_info:
    kind: Deployment
    namespace: "{{ awx_namespace }}"
    name: awx-operator-controller-manager
    wait: true
    wait_sleep: 10
    wait_timeout: 300
  register: awx_operator_controller_manager_pods
