---

- name: Ensure required variables are valid
  ansible.builtin.assert:
    that:
      - service_type in ['nodeport', 'ingress']
    quiet: true
    fail_msg: "Required variables are invalid, take a look at defaults/main.yml for additional info."

- name: Expose AWX via NodePort
  when: service_type == 'nodeport'
  block:
    - name: Expose port {{ awx_instance_port }}
      kubernetes.core.k8s_service:
        namespace: "{{ awx_namespace }}"
        name: "{{ awx_instance_name }}-service"
        type: NodePort
        ports:
          - port: 80
            target_port: 80
            nodePort: "{{ awx_instance_port }}"
        selector:
          app.kubernetes.io/component: awx
          app.kubernetes.io/managed-by: awx-operator
          app.kubernetes.io/name: "{{ awx_instance_name }}-web"
        state: present

- name: Expose AWX via Ingress
  when: service_type == 'ingress'
  block:
    - name: Create TLS key and certificate
      ansible.builtin.import_tasks: certificate.yml
