---

- name: Deploy AWX instance
  kubernetes.core.k8s:
    namespace: "{{ awx_namespace }}"
    definition: "{{ lookup('template', 'awx_definition.yml.j2') }}"
    state: present

- name: Wait for running state of AWX deployment (timeout set to 10 minutes)
  kubernetes.core.k8s_info:
    kind: Deployment
    namespace: "{{ awx_namespace }}"
    name: "{{ awx_instance_name }}-web"
    wait: true
    wait_sleep: 10
    wait_timeout: 600
