---

- name: Install module requirements
  ansible.builtin.package:
    name: python3-cryptography
    state: present
  become: true

- name: Create private key
  community.crypto.openssl_privatekey:
    path: "{{ certificate_directory }}/tls.key"

- name: Get state of private key
  ansible.builtin.stat:
    path: "{{ certificate_directory }}/tls.key"
  register: private_key_file

- name: Create CSR
  community.crypto.openssl_csr:
    path: "{{ certificate_directory }}/tls.csr"
    privatekey_path: "{{ certificate_directory }}/tls.key"
    subject:
      C: DE
      ST: NRW
      L: Ratingen
      O: Computacenter AG & Co. oHG
      OU: Ansible Community
      CN: "{{ awx_endpoint_name }}"
    subject_alt_name:
      - "DNS:{{ ansible_fqdn }}"
      - "DNS:{{ ansible_hostname }}"
      - "IP:{{ ansible_default_ipv4.address }}"
  when: private_key_file.stat.exists

- name: Get state of CSR
  ansible.builtin.stat:
    path: "{{ certificate_directory }}/tls.key"
  register: csr_file

- name: Create self-signed certificate from CSR
  community.crypto.x509_certificate:
    path: "{{ certificate_directory }}/tls.crt"
    privatekey_path: "{{ certificate_directory }}/tls.key"
    csr_path: "{{ certificate_directory }}/tls.csr"
    provider: selfsigned
    mode: "0755"
  when:
    - private_key_file.stat.exists
    - csr_file.stat.exists
