---

- ansible.builtin.import_tasks: requirements.yml  # noqa name[missing]

- ansible.builtin.import_tasks: storage.yml # noqa name[missing]
  when: storage_configuration

- ansible.builtin.import_tasks: awx_operator_deployment.yml # noqa name[missing]

- ansible.builtin.import_tasks: awx_instance_installation.yml # noqa name[missing]

- ansible.builtin.import_tasks: awx_instance_service.yml # noqa name[missing]

- ansible.builtin.import_tasks: awx_instance_info.yml # noqa name[missing]
  tags:
    - info
    - password

- ansible.builtin.import_tasks: uninstall.yml # noqa name[missing]
  when: '"uninstall" in ansible_run_tags'
  tags:
    - uninstall
