---

- name: Install system dependencies for module functionality
  ansible.builtin.package:
    name:
      - python3-pip
      - git
    state: present
  become: true

- name: Install kubernetes Python package for module functionality
  ansible.builtin.pip:
    name: kubernetes
    state: present
