---

- name: Delete AWX instance
  kubernetes.core.k8s:
    namespace: "{{ awx_namespace }}"
    api_version: awx.ansible.com/v1beta1
    kind: AWX
    name: "{{ awx_instance_name }}"
    wait: true
    state: absent

- name: Delete AWX operator
  kubernetes.core.k8s:
    namespace: "{{ awx_namespace }}"
    kind: Deployment
    name: awx-operator-controller-manager
    wait: true
    state: absent

- name: Delete AWX operator metrics service
  kubernetes.core.k8s:
    namespace: "{{ awx_namespace }}"
    kind: Service
    name: awx-operator-controller-manager-metrics-service
    wait: true
    state: absent

- name: Delete AWX namespace
  kubernetes.core.k8s:
    kind: Namespace
    name: "{{ awx_namespace }}"
    wait: true
    state: absent
