---

# Certificate-related variables
certificate_directory: "{{ ansible_user_dir }}"

# Instance-related variables
awx_instance_name: awx-demo

# Operator-related variables
# awx_operator_tag: # when unset 'latest' is used
awx_namespace: awx
kustomize_directory: "{{ ansible_user_dir }}"

# Service/Network-related variables
service_type: nodeport
exposed_node_port: 30080
awx_endpoint_name: awx.demo.com

# Storage-related variables
storage_configuration: false
awx_database_volume_name: awx-postgres-volume
awx_database_volume_capacity: 8Gi
awx_database_volume_host_path: /data/{{ awx_instance_name }}-postgres-data
