---

- name: Install Python3 package manager
  ansible.builtin.package:
    name: python3-pip
    state: present
  become: true

- name: Install kubernetes Python package for module functionality
  ansible.builtin.pip:
    name: kubernetes
    state: present

- name: Stop and disable firewalld
  ansible.builtin.service:
    name: firewalld
    state: stopped
    enabled: false
